spring.application.name=securityProject
server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/securitypos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=2436

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

#spring.security.user.name=tharika
#spring.security.user.password=1234
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
